// Generated by gencpp from file hector_mapping/ResetMappingResponse.msg
// DO NOT EDIT!


#ifndef HECTOR_MAPPING_MESSAGE_RESETMAPPINGRESPONSE_H
#define HECTOR_MAPPING_MESSAGE_RESETMAPPINGRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hector_mapping
{
template <class ContainerAllocator>
struct ResetMappingResponse_
{
  typedef ResetMappingResponse_<ContainerAllocator> Type;

  ResetMappingResponse_()
    {
    }
  ResetMappingResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::hector_mapping::ResetMappingResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hector_mapping::ResetMappingResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ResetMappingResponse_

typedef ::hector_mapping::ResetMappingResponse_<std::allocator<void> > ResetMappingResponse;

typedef boost::shared_ptr< ::hector_mapping::ResetMappingResponse > ResetMappingResponsePtr;
typedef boost::shared_ptr< ::hector_mapping::ResetMappingResponse const> ResetMappingResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hector_mapping::ResetMappingResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hector_mapping::ResetMappingResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace hector_mapping

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hector_mapping::ResetMappingResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hector_mapping::ResetMappingResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hector_mapping::ResetMappingResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hector_mapping::ResetMappingResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hector_mapping::ResetMappingResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hector_mapping::ResetMappingResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hector_mapping::ResetMappingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::hector_mapping::ResetMappingResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::hector_mapping::ResetMappingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hector_mapping/ResetMappingResponse";
  }

  static const char* value(const ::hector_mapping::ResetMappingResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hector_mapping::ResetMappingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::hector_mapping::ResetMappingResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hector_mapping::ResetMappingResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResetMappingResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hector_mapping::ResetMappingResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::hector_mapping::ResetMappingResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // HECTOR_MAPPING_MESSAGE_RESETMAPPINGRESPONSE_H
