environment:
  SITL_SPEEDUP: 10
  SITL_RATE: 200
  PYTHONUNBUFFERED: 1

  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7"
    - PYTHON: "C:\\Python37"
      PYTHON_VERSION: "3.7"

cache:
  - "c:\\Users\\appveyor\\.pip-wheelhouse"

init:
  - cmd: "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

install:
  - ps: |
      New-Item -ItemType Directory -Force -Path c:\Users\appveyor\pip\
      @'
      [global]
      find-links = file://c:/Users/appveyor/.pip-wheelhouse

      [wheel]
      wheel-dir = c:/Users/appveyor/.pip-wheelhouse
      '@ | out-file -Encoding ascii -FilePath c:\Users\appveyor\pip\pip.ini
  - cmd: 'python -m pip install pip wheel -U'
  - cmd: 'pip install . -UI'
  - cmd: 'pip install -r requirements.txt -UI'

build: off

test_script:
  - cmd: 'nosetests -svx dronekit.test.unit'
  - cmd: 'nosetests -svx dronekit.test.sitl'

clone_depth: 10
